
# coding: utf-8
from sqlalchemy import BigInteger, Column, Date, DateTime, Enum, Index, Integer, String, Text, text
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class IcimsJobPosting(Base):
    __tablename__ = 'icims_JobPostings'

    id = Column(Integer, primary_key=True)
    additionallocations = Column(String(45))
    location = Column(Text)
    assessmenttype = Column(String(45))
    bgcpackagetype = Column(String(45))
    billingcode = Column(String(45))
    bonus = Column(String(45))
    commission = Column(String(45))
    confidence = Column(Integer)
    costcenter = Column(String(45))
    drugscreenpackage = Column(String(45))
    duedate = Column(Date)
    education = Column(String(45))
    eeocategory = Column(String(45))
    enddate = Column(Date)
    experienceyears = Column(Integer)
    externalid = Column(String(45))
    fee = Column(String(45))
    field12235 = Column(String(45))
    jcf2002 = Column(String(45))
    jcf2004 = Column(String(45))
    jcf2005 = Column(String(45))
    jcf2006 = Column(Date)
    jcf2007 = Column(String(45))
    jcf2008 = Column(String(45))
    folder = Column(String(45))
    hiretype = Column(String(45))
    hiringmanager = Column(String(45))
    industry = Column(String(45))
    jobid = Column(String(45))
    joblength = Column(String(45))
    joblocation = Column(String(45))
    jobnumber = Column(String(45))
    jobowner = Column(String(45))
    jobpostend = Column(Date)
    jobpoststart = Column(Date)
    jobtemplate = Column(Text)
    jobtitle = Column(String(45))
    jobtype = Column(String(45))
    maximumsalary = Column(String(45))
    minimumsalary = Column(String(45))
    newhirecategory = Column(String(45))
    numberofpositions = Column(Integer)
    overview = Column(Text)
    percentofbase = Column(Integer)
    positioncategory = Column(String(45))
    positionlevel = Column(String(45))
    positiontype = Column(String(45))
    priority = Column(String(45))
    qualifications = Column(Text)
    rate = Column(String(45))
    recruiter = Column(String(45))
    replacing = Column(String(45))
    responsibilities = Column(String(45))
    skillset = Column(String(45))
    skill = Column(String(45))
    skilllevel = Column(String(45))
    startdate = Column(Date)
    travel = Column(String(45))
    videointerviewpackage = Column(String(45))
    visa = Column(String(45))

